package org.intellij.plugins.export.keymap.model

import org.intellij.plugins.export.keymap.Bundle

/**
 * @author Denis Zhdanov
 * @since 6/21/12 1:13 PM
 */
class CommonActionsProfile extends ActionsProfile {

    CommonActionsProfile() {
        name = Bundle.message("profile.name.default")
        entries = [new Header(depth: 0, name: 'Editing'),
                   new ActionData(id: ['CodeCompletion'], description: 'Basic Code Completion'),
                   new ActionData(id: ['SmartTypeCompletion'], description: 'Smart Code Completion'),
                   new ActionData(id: ['ClassNameCompletion'], description: 'Type Name Completion'),
                   new ActionData(id: ['EditorCompleteStatement'], description: 'Complete Statement'),
                   new ActionData(id: ['ParameterInfo'], description: 'Parameter Information'),
                   new ActionData(id: ['QuickJavaDoc','ExternalJavaDoc'], description: 'Quick/External Documentation'),
                   //new ActionData(id: ['ExternalJavaDoc'], description: 'External documentation'),
                   new ActionData(shortcut: 'Ctrl+mouse over', description: 'Brief Information'),
                   new ActionData(id: ['ShowErrorDescription'], description: 'Show Error Description'),
                   new ActionData(id: ['NewElement'], description: 'Generate Code'),
                   new ActionData(id: ['OverrideMethods','ImplementMethods'], description: 'Override/Implement Members'),
//                   new ActionData(id: ['ImplementMethods']),
                   new ActionData(id: ['SurroundWith']),
                   new ActionData(id: ['CommentByLineComment','CommentByBlockComment'], description: 'Comment with Line/Block Comment'),
//                   new ActionData(id: ['CommentByBlockComment']),
                   new ActionData(id: ['EditorSelectWord', 'EditorUnSelectWord'], description: 'Extend/Shrink Selection'),
                   new ActionData(id: ['EditorContextInfo']),
                   new ActionData(id: ['ShowIntentionActions']),
                   new ActionData(id: ['ReformatCode']),
                   new ActionData(id: ['OptimizeImports']),
                   new ActionData(id: ['AutoIndentLines']),
//                   new ActionData(id: ['EditorIndentSelection', 'EditorUnindentSelection'], description: 'Indent/Unindent selected lines'),
                   new ActionData(id: ['$Cut', '$Copy', '$Paste'], description: 'Cut/Copy/Paste'),
//                   new ActionData(id: ['$Copy']),
//                   new ActionData(id: ['$Paste']),
                   new ActionData(id: ['PasteMultiple'], description: 'Paste from Clipboard History'),
                   new ActionData(id: ['EditorDuplicate'], description: 'Duplicate Current Line or Selection'),
                   new ActionData(id: ['EditorDeleteLine'], description: 'Delete Line at Caret'),
                   new ActionData(id: ['EditorJoinLines', 'EditorSplitLine'], description: 'Join/Split Line'),
//                   new ActionData(id: ['EditorSplitLine'], description: 'Smart line split'),
                   new ActionData(id: ['EditorStartNewLine'], description: 'Start New Line'),
                   new ActionData(id: ['EditorToggleCase'], description: 'Toggle Case'),
//                   new ActionData(id: ['EditorCodeBlockEndWithSelection', 'EditorCodeBlockStartWithSelection'],
//                           description: 'Select till code block end/start'),
//                   new ActionData(id: ['EditorDeleteToWordEnd'], description: 'Delete to word end'),
//                   new ActionData(id: ['EditorDeleteToWordStart'], description: 'Delete to word start'),
                   new ActionData(id: ['ExpandRegion', 'CollapseRegion'], description: 'Expand/Collapse Code Block'),
                   new ActionData(id: ['ExpandAll'], description: 'Expand All'),
                   new ActionData(id: ['CollapseAll'], description: 'Collapse All'),
                   new ActionData(id: ['SaveAll']),
                   new ActionData(id: ['CloseContent']),

                   new Header(depth: 0, name: 'General'),
//                   new ActionData(id: ['ActivateMessagesToolWindow', 'ActivateProjectToolWindow', 'ActivateFavoritesToolWindow', 'ActivateFindToolWindow',
//                                       'ActivateRunToolWindow', 'ActivateDebugToolWindow', 'ActivateTODOToolWindow', 'ActivateStructureToolWindow',
//                                       'ActivateHierarchyToolWindow', 'ActivateChangesToolWindow'],
//                           shortcut: 'Alt + #[0-9]',
//                           description: 'Open corresponding tool window'),

                   new ActionData(id: ['Synchronize']),
                   new ActionData(id: ['ToggleFullScreen']),
                   new ActionData(id: ['HideAllWindows']),
                   new ActionData(id: ['AddToFavoritesPopup']),
//                   new ActionData(id: ['CodeInspection.OnEditor']),
                   new ActionData(id: ['QuickChangeScheme']),
                   new ActionData(id: ['ShowSettings']),
                   new ActionData(id: ['ShowProjectStructureSettings']),
                   new ActionData(id: ['GotoAction']),
                   new ActionData(id: ['NextSplitter']),

                   new ColumnBreak(),

                   new Header(depth: 0, name: 'Debugging'),
                   new ActionData(id: ['CompileDirty']),
                   new ActionData(id: ['Compile']),
                   new ActionData(id: ['ChooseRunConfiguration']),
                   new ActionData(id: ['ChooseDebugConfiguration']),
                   new ActionData(id: ['Run']),
                   new ActionData(id: ['Debug']),
                   new ActionData(id: ['StepOver']),
                   new ActionData(id: ['StepInto']),
                   new ActionData(id: ['SmartStepInto']),
                   new ActionData(id: ['StepOut']),
                   new ActionData(id: ['RunToCursor']),
                   new ActionData(id: ['EvaluateExpression']),
                   new ActionData(id: ['Resume']),
                   new ActionData(id: ['ToggleLineBreakpoint']),
                   new ActionData(id: ['ViewBreakpoints']),

                   new Header(depth: 0, name: 'Unit Testing'),
                   new ActionData(id: ['RiderUnitTestQuickListPopupAction']),
                   new ActionData(id: ['RiderUnitTestRunContextAction']),
                   new ActionData(id: ['RiderUnitTestDebugContextAction']),
                   new ActionData(id: ['RiderUnitTestSessionAbortAction']),
                   new ActionData(id: ['RiderUnitTestRepeatPreviousRunAction']),
                   new ActionData(id: ['RiderUnitTestSessionRerunFailedTestsAction']),
                   new ActionData(id: ['RiderUnitTestRunSolutionAction']),
                   new ActionData(id: ['RiderUnitTestNewSessionAction']),
                   new ActionData(id: ['RiderUnitTestAppendTestsAction']),
                   new ActionData(id: ['RiderUnitTestRunCurrentSessionAction']),

                   new Header(depth: 0, name: 'Refactoring'),
                   new ActionData(id: ['CopyElement']),
                   new ActionData(id: ['Move']),
                   new ActionData(id: ['SafeDelete']),
                   new ActionData(id: ['RenameElement']),
                   new ActionData(id: ['ChangeSignature']),
                   new ActionData(id: ['Inline']),
                   new ActionData(id: ['ExtractMethod'], description: 'Extract Method'),
                   new ActionData(id: ['IntroduceVariable'], description: 'Introduce Variable'),
                   new ActionData(id: ['IntroduceField'], description: 'Introduce Field'),
                   new ActionData(id: ['IntroduceConstant'], description: 'Introduce Constant'),
                   new ActionData(id: ['IntroduceParameter'], description: 'Introduce Parameter'),

                   new Header(depth: 0, name: 'VCS/Local History'),
                   new ActionData(id: ['Vcs.QuickListPopupAction']),
                   new ActionData(id: ['CheckinProject']),
                   new ActionData(id: ['Vcs.UpdateProject']),
                   new ActionData(id: ['RecentChanges']),
                   new ActionData(id: ['ChangesView.Revert']),
                   new ActionData(id: ['Vcs.Push']),
                   new ActionData(id: ['VcsShowNextChangeMarker']),
                   new ActionData(id: ['VcsShowPrevChangeMarker']),

//      new Header(depth: 0, name: 'Live Templates'),
//      new ActionData(id: ['SurroundWithLiveTemplate']),
//      new ActionData(id: ['InsertLiveTemplate']),
//      new ActionData(shortcut: 'iter', description: 'Iteration according to Java SDK 1.5 style'),
//      new ActionData(shortcut: 'inst', description: 'Check object type with instanceof and downcast it'),
//      new ActionData(shortcut: 'itco', description: 'Iterate elements of java.util.Collection'),
//      new ActionData(shortcut: 'itit', description: 'Iterate elements of java.util.Iterator'),
//      new ActionData(shortcut: 'itli', description: 'Iterate elements of java.util.List'),
//      new ActionData(shortcut: 'psf',  description: 'public static final'),
//      new ActionData(shortcut: 'thr',  description: 'throw new'),

                   new ColumnBreak(),

                   new Header(depth: 0, name: 'Search/Replace'),
                   new ActionData(id: ['Find']),
                   new ActionData(id: ['Replace']),
                   new ActionData(id: ['FindNext'], description: 'Find Next Occurence'),
                   new ActionData(id: ['FindPrevious'], description: 'Find Previous Occurence'),
                   new ActionData(id: ['FindInPath']),
                   new ActionData(id: ['ReplaceInPath']),
                   new ActionData(id: ['StructuralSearchPlugin.StructuralSearchAction'], description: 'Search Structurally'),
                   new ActionData(id: ['StructuralSearchPlugin.StructuralReplaceAction'], description: 'Replace Structurally'),

                   new Header(depth: 0, name: 'Usage Search'),
                   new ActionData(id: ['FindUsages', 'FindUsagesInFile'], description: 'Find Usages / Find Usages in File'),
                   new ActionData(id: ['HighlightUsagesInFile']),
                   new ActionData(id: ['ShowUsages']),

                   new Header(depth: 0, name: 'Navigation'),
                   new ActionData(id: ['SearchEverywhere'], shortcut: 'Double Shift'),
                   new ActionData(id: ['GotoClass']),
                   new ActionData(id: ['GotoFile']),
                   new ActionData(id: ['GotoSymbol']),
                   new ActionData(id: ['NextTab', 'PreviousTab'], description: 'Go to next/previous editor tab'),
                   new ActionData(id: ['JumpToLastWindow']),
                   new ActionData(id: ['EditorEscape'], description: 'Go to editor (from tool window)'),
                   new ActionData(id: ['HideActiveWindow']),
                   new ActionData(id: ['CloseActiveTab']),
                   new ActionData(id: ['GotoLine']),
                   new ActionData(id: ['RecentFiles']),
                   new ActionData(id: ['Back', 'Forward'], description: 'Navigate back/forward'),
                   new ActionData(id: ['JumpToLastChange']),
                   new ActionData(id: ['SelectIn']),
                   new ActionData(id: ['GotoDeclaration']),
                   new ActionData(id: ['GotoImplementation']),
                   new ActionData(id: ['QuickImplementations']),
                   new ActionData(id: ['GotoTypeDeclaration']),
                   new ActionData(id: ['GotoSuperMethod']),
                   new ActionData(id: ['MethodUp', 'MethodDown'], description: 'Go to previous/next method'),
                   new ActionData(id: ['EditorCodeBlockEnd', 'EditorCodeBlockStart'], description: 'Move to code block end/start'),
                   new ActionData(id: ['FileStructurePopup']),
                   new ActionData(id: ['TypeHierarchy']),
                   new ActionData(id: ['MethodHierarchy']),
                   new ActionData(id: ['CallHierarchy']),
                   new ActionData(id: ['GotoNextError', 'GotoPreviousError'], description: 'Next/previous highlighted error'),
                   new ActionData(id: ['EditSource']),
                   new ActionData(id: ['ShowNavBar']),
                   new ActionData(id: ['ToggleBookmark']),
                   new ActionData(id: ['ToggleBookmarkWithMnemonic'], description: 'Toggle bookmark with mnemonic'),
                   new ActionData(id: ['GotoBookmark0', 'GotoBookmark1', 'GotoBookmark2', 'GotoBookmark3', 'GotoBookmark4', 'GotoBookmark5',
                                       'GotoBookmark6', 'GotoBookmark7', 'GotoBookmark8', 'GotoBookmark9'],
                           shortcut: 'Ctrl + #[0-9]',
                           description: 'Go to numbered bookmark'),
                   new ActionData(id: ['ShowBookmarks'])
        ]
    }
}
